name: wt_app_scaffold
description: A new Flutter package project.
version: 0.0.5
publish_to: 'none'
homepage: https://github.com/tmcmaster/et-app-scaffold

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  curved_navigation_bar:
  draggable_bottom_sheet:
  firebase_auth:
  firebase_core:
  firebase_ui_auth: ^1.0.3
  firebase_ui_localizations:
  firebase_ui_oauth_apple: ^1.0.3
  firebase_ui_oauth_facebook: ^1.0.3
  firebase_ui_oauth_google: ^1.0.3
  firebase_ui_oauth_twitter: ^1.0.3
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  font_awesome_flutter:
  form_builder_validators:
  grouped_list:
  hooks_riverpod:
  logger:
  wt_action_button:
    git: https://github.com/tmcmaster/wt_action_button.git
  wt_firepod:
    git: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git
  wt_settings:
    git: https://github.com/tmcmaster/wt_settings.git

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_lints:
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  wt_action_button:
#    path: ../wt_action_button
#  wt_firepod:
#    path: ../wt_firepod
#  wt_logging:
#    path: ../wt_logging
#  wt_models:
#    path: ../wt_models
#  wt_settings:
#    path: ../wt_settings

flutter:
  uses-material-design: true
  assets:
    - assets/
