name: wt_app_scaffold
description: A package to manage the structure and navigation of an app.
version: 1.0.0+1
publish_to: 'none'
homepage: https://github.com/tmcmaster/et-app-scaffold

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  cloud_firestore: ^4.9.1
  cloud_functions: ^4.3.4
  collection: ^1.17.2
  color_blindness: ^0.1.2
  curved_navigation_bar: ^1.0.3
  device_preview: ^1.1.0
  draggable_bottom_sheet: ^1.0.2
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_database: ^10.2.4
  firebase_storage: ^11.2.6
  firebase_ui_auth: ^1.6.0
  firebase_ui_localizations: ^1.5.0
  firebase_ui_oauth_apple: ^1.0.3
  firebase_ui_oauth_google: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  form_builder_validators: ^9.0.0
  go_router: ^10.1.2
  grouped_list: ^5.1.2
  logger: ^1.4.0
  package_info_plus: ^4.1.0
  wt_action_button:
    git: https://github.com/tmcmaster/wt_action_button.git
  wt_firepod:
    git: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git
  wt_settings:
    git: https://github.com/tmcmaster/wt_settings.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
