name: wt_app_scaffold
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logger:
  grouped_list:
  font_awesome_flutter:
  flutter_riverpod:
  hooks_riverpod:
  draggable_bottom_sheet:
  curved_navigation_bar:
  firebase_ui_auth: ^1.0.3
  firebase_ui_oauth_google: ^1.0.3
  firebase_ui_oauth_apple: ^1.0.3
  firebase_ui_oauth_facebook: ^1.0.3
  firebase_ui_oauth_twitter: ^1.0.3
  wt_action_button:
    git: git@github.com:tmcmaster/wt_action_button.git

  # TODO: need to move these packages into their own projects
  settings:
    path: ./packages/settings
  firepod:
    path: ./packages/firepod
  utils:
    path: ./packages/utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4


flutter:
