name: wt_app_scaffold
description: A new Flutter package project.
version: 0.0.5
publish_to: 'none'
homepage: https://github.com/tmcmaster/et-app-scaffold

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logger:
  grouped_list:
  font_awesome_flutter:
  flutter_riverpod:
  flutter_hooks:
  hooks_riverpod:
  draggable_bottom_sheet:
  curved_navigation_bar:
  firebase_core:
  firebase_auth:
  firebase_ui_localizations:
  firebase_ui_auth: ^1.0.3
  firebase_ui_oauth_google: ^1.0.3
  firebase_ui_oauth_apple: ^1.0.3
  firebase_ui_oauth_facebook: ^1.0.3
  firebase_ui_oauth_twitter: ^1.0.3
  form_builder_validators:
  wt_action_button:
    git: git@github.com:tmcmaster/wt_action_button.git
  wt_models:
    git: git@github.com:tmcmaster/wt_models.git
  wt_settings:
    git: git@github.com:tmcmaster/wt_settings.git
  wt_firepod:
    git: git@github.com:tmcmaster/wt_firepod.git
  wt_logging:
    git: git@github.com:tmcmaster/wt_logging.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4

#dependency_overrides:
#  wt_action_button:
#    path: ../wt_action_button
#  wt_models:
#    path: ../wt_models
#  wt_settings:
#    path: ../wt_settings
#  wt_firepod:
#    path: ../wt_firepod
#  wt_logging:
#    path: ../wt_logging

flutter:
