name: wt_app_scaffold
description: A package to manage the structure and navigation of an app.
version: 1.1.0+3
publish_to: 'none'
homepage: https://github.com/tmcmaster/et-app-scaffold

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/

dependencies:
  collection: ^1.17.2
  color_blindness: ^0.1.2
  curved_navigation_bar: ^1.0.3
  device_info_plus: ^9.1.1
  device_preview: ^1.1.0
  draggable_bottom_sheet: ^1.0.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  grouped_list: ^5.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  webview_universal: ^0.0.5
  wt_action_button:
    git: https://github.com/tmcmaster/wt_action_button.git
  wt_logging:
    git: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git
  wt_settings:
    git: https://github.com/tmcmaster/wt_settings.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:

#dependency_overrides:
#  wt_logging:
#    path: ../wt_logging