name: wt_app_scaffold
description: A package to manage the structure and navigation of an app.
version: 1.1.0+3
publish_to: 'none'
homepage: https://github.com/tmcmaster/et-app-scaffold

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.29.2'

flutter:
  uses-material-design: true
  assets:
    - assets/

dependencies:
  collection: 
  color_blindness: 
  curved_navigation_bar: 
  device_info_plus: 
  device_preview:
    git:
      url: git@github.com:tmcmaster/device_preview.git
      path: device_preview
  draggable_bottom_sheet: 
  flutter:
    sdk: flutter
#  flutter_inappwebview: ^6.0.0
#  flutter_inappwebview_macos: ^1.0.11
#  flutter_localizations:
#    sdk: flutter
  flutter_riverpod: 
  flutter_svg: 
  font_awesome_flutter: 
  form_builder_validators: 
  freezed_annotation: 
  go_router: 
  grouped_list: 
  intl: 
  json_annotation: 
  logger: 
  package_info_plus: 
  path_provider: 
#  webview_flutter:
#  webview_flutter_android:
#  webview_flutter_wkwebview:
#  webview_universal:
  wt_action_button:
    git: git@github.com:tmcmaster/wt_action_button.git
  wt_logging:
    git: git@github.com:tmcmaster/wt_logging.git
  wt_models:
    git: git@github.com:tmcmaster/wt_models.git
  wt_settings:
    git: git@github.com:tmcmaster/wt_settings.git

dev_dependencies:
  build_runner: 
  flutter_launcher_icons: 
  flutter_native_splash: 
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:

dependency_overrides:
#  device_preview:
#    path: ../../fork/device_preview/device_preview
#  wt_action_button:
#    path: ../wt_action_button
  wt_logging:
    path: ../wt_logging
#  wt_models:
#    path: ../wt_models
#  wt_settings:
#    path: ../wt_settings
