name: firepod
description: Firepod is a library for loading data from firebase using riverpod.

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  utils:
    path: ../utils
  settings:
    path: ../settings
  shared_preferences:
  crypto:
  freezed_annotation:
  font_awesome_flutter:
  flutter_riverpod:
  hooks_riverpod:
  firebase_auth:
  firebase_core:
  firebase_database:
  firebase_remote_config:
  cloud_functions:
  google_sign_in:
  sign_in_with_apple:
