name: firepod
description: Firepod is a library for loading data from firebase using riverpod.

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wt_models:
    git: git@github.com:tmcmaster/wt_models.git
  settings:
    path: ../settings
  shared_preferences:
  crypto:
  logger:
  riverpod: ^2.0.2
  freezed_annotation:
  font_awesome_flutter:
  flutter_riverpod:
  hooks_riverpod:
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_database: ^10.0.3
  firebase_remote_config: ^3.0.3
  cloud_functions: ^4.0.3
  #  google_sign_in: ^5.4.2
#  sign_in_with_apple: ^4.1.0
  firebase_ui_auth: ^1.0.3
  firebase_ui_oauth_google: ^1.0.3
  firebase_ui_oauth_apple: ^1.0.3
  firebase_ui_oauth_facebook: ^1.0.3
  firebase_ui_oauth_twitter: ^1.0.3