name: job_state_button
description: Button that is aware of the action that is being done.

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.0.2
  hooks_riverpod:
  flutter_hooks:
  flutter_riverpod:
  utils:
    path: ../utils