name: settings
description: Settings package

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  utils:
    path: ../utils
  riverpod: ^2.0.2
  hooks_riverpod:
  shared_preferences:
  date_time_picker: ^2.1.0
  spring_button: ^2.0.0
#  fast_color_picker: ^0.1.1
