name: wt_app_scaffold_examples
description: Show examples of using the wt_app_scaffold package.
publish_to: none
version: 1.0.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  firebase_database:
  firebase_ui_auth:
  flutter:
    sdk: flutter
#  flutter_inappwebview:
  flutter_riverpod:
  font_awesome_flutter:
  form_builder_validators:
  freezed_annotation: ^2.4.4
  json_annotation: 4.9.0
  go_router:
  path_provider:
  url_launcher:
#  webview_flutter:
#  webview_flutter_android:
#  webview_flutter_platform_interface:
#  webview_flutter_web:
#  webview_flutter_wkwebview:
  wt_action_button:
    git: git@github.com:tmcmaster/wt_action_button.git
  wt_app_scaffold:
    git: git@github.com:tmcmaster/wt_app_scaffold.git
  wt_firepod:
    git: git@github.com:tmcmaster/wt_firepod.git
  wt_firepod_list_view:
    git: git@github.com:tmcmaster/wt_firepod_list_view.git
  wt_logging:
    git: git@github.com:tmcmaster/wt_logging.git
  wt_models:
    git: git@github.com:tmcmaster/wt_models.git
  wt_settings:
    git: git@github.com:tmcmaster/wt_settings.git

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable:

dependency_overrides:
  wt_action_button:
    path: ../../wt_action_button
  wt_app_scaffold:
    path: ..
  wt_firepod:
    path: ../../wt_firepod
  wt_logging:
    path: ../../wt_logging
  wt_settings:
    path: ../../wt_settings

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: assets/avocado.png
  android: true
  ios: true

flutter_native_splash:
  color: "#9E9E9E"
  image: assets/avocado.png
  android_12:
  web_image_mode: center

