name: sample_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  font_awesome_flutter:
  wt_app_scaffold:
    path: ..
  riverpod: ^2.0.2
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_database: ^10.0.3
  firebase_remote_config: ^3.0.3
  cloud_functions: ^4.0.3
#  google_sign_in: ^5.4.2
#  sign_in_with_apple: ^4.1.0
  firebase_ui_auth: ^1.0.3
  firebase_ui_oauth_google: ^1.0.3
  firebase_ui_oauth_apple: ^1.0.3
  firebase_ui_oauth_facebook: ^1.0.3
  firebase_ui_oauth_twitter: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: assets/avocado.png
  android: true
  ios: true

flutter_native_splash:
  color: "#9E9E9E"
  image: assets/avocado.png
  android_12:
  web_image_mode: center
