name: wt_app_scaffold_examples
description: Show examples of using the wt_app_scaffold package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  cupertino_icons:
  firebase_auth:
  firebase_core:
  firebase_database:
  firebase_ui_auth:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  form_builder_validators:
  freezed:
  freezed_annotation: 
  hooks_riverpod:
  riverpod:
  wt_action_button:
    git: https://github.com/tmcmaster/wt_action_button.git
  wt_app_scaffold:
    path: ..
  wt_firebase_listview:
    git: https://github.com/tmcmaster/wt_firebase_listview.git
  wt_firepod:
    git: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git
  wt_settings:
    git: https://github.com/tmcmaster/wt_settings.git

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: assets/avocado.png
  android: true
  ios: true

flutter_native_splash:
  color: "#9E9E9E"
  image: assets/avocado.png
  android_12:
  web_image_mode: center
