name: wt_app_scaffold_examples
description: Show examples of using the wt_app_scaffold package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  check: dart analyze
  fix: dart fix --dry-run
  freezed:
    build: flutter pub run build_runner build --delete-conflicting-outputs
  macos:
    pod:
      fix: (cd macos; rm Podfile.lock; pod install --repo-update)

dependencies:
  cupertino_icons: ^1.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_database: ^11.1.1
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router:
  path_provider: ^2.1.4
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
#  webview_flutter_platform_interface: ^2.6.0
#  webview_flutter_web: ^0.2.2+3
  webview_flutter_wkwebview: ^3.9.4
  wt_action_button:
    git: https://github.com/tmcmaster/wt_action_button.git
  wt_app_scaffold:
    git: https://github.com/tmcmaster/wt_app_scaffold.git
  wt_firebase_listview:
    git: https://github.com/tmcmaster/wt_firebase_listview.git
  wt_firepod:
    git: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git
  wt_settings:
    git: https://github.com/tmcmaster/wt_settings.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

#dependency_overrides:
#  wt_app_scaffold:
#    path: ..
#  wt_firepod:
#    path: ../../../libraries/wt_firepod
#  wt_logging:
#    path: ../../../libraries/wt_logging
#  wt_settings:
#    path: ../../../libraries/wt_settings

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: assets/avocado.png
  android: true
  ios: true

flutter_native_splash:
  color: "#9E9E9E"
  image: assets/avocado.png
  android_12:
  web_image_mode: center

